### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by stepanenko3** [wemersonrv/input-mask#10]

**Comment by wemersonrv** [comment]
> _No description provided._

Add support to nova 4, require a refactor on the code because it uses Inertiajs and i don't know exactly changes need to do because need to learn Inertia first. And I haven't even used the nova 4 yet and with my current projects i think only in a couple of months to do that.

Sorry but for now i cannot do the changes. But a Pull Request with the changes you need will be very wellcome. Feel free to add your contribution.
