### ISSUE TITLE
Mask Money

### ISSUE THREAD

**Issue by fredroo** [wemersonrv/input-mask#3]
is possible in your nova package mask money (BRL)? when masked 1000 gonna turn 1.000,00

**Comment by fredroo** [comment]
@wemersonrv can you help me?

**Comment by wemersonrv** [comment]
i think it's possible, because uses [Vue The Mask](https://github.com/vuejs-tips/vue-the-mask) component, and it's very extensible. But i need to study it more to understand how to add this in a good way and my time to do this now is too busy these last weeks... so it will be a little bit slowly, but i will check it..

What do you think? Apply mask when input lost focus?

**Comment by fredroo** [comment]
Great, thanks, I will be waiting

Apply when keydown or keyup, to user look mask in use for assist you when filling forms

**Comment by fredroo** [comment]
@wemersonrv https://vuejs-tips.github.io/v-money/

**Comment by fredroo** [comment]
@wemersonrv can you use 
https://vuejs-tips.github.io/v-money/
for add mask money in R$ to your project?

**Comment by wemersonrv** [comment]
> @wemersonrv can you use
> https://vuejs-tips.github.io/v-money/
> for add mask money in R$ to your project?

Hello @fredroo sorry for the delay. I'm will check it in next weekend.

I believe it's possible to use it. Will make some tests first!

**Comment by fredroo** [comment]
@wemersonrv any new?

**Comment by wemersonrv** [comment]
> @wemersonrv any new?

Hello, not yet sorry! I'm overwhelmed with a lot of projects and there is no time left to check further.

But, a PR with your needs would be welcome!

**Comment by fredroo** [comment]
ok no problem, maybe I can solve this and send here to you approve

**Comment by fredroo** [comment]
@wemersonrv, I ask the owner of this project https://github.com/vyuldashev/nova-money-field

if him can implement BRL money
